


if __name__ == "__main__":
    print("WELCOME TO COMMAND LINE OF ARCANE BOT")

    print("THERE ARE A LOTS OF DIFFERENT FUNCTIONALITY I CAN PERFORM FOR YOU")
    print("PLEASE GUIDE ME, AND I WILL HELP YOU!")
